
# קבועים עבור צבעים וחלקי המשחק
VALID_COLORS = {'w', 'b'}
VALID_PIECES = {'K', 'Q', 'R', 'B', 'N', 'P'}

EMPTY_CELL = "."
SPACE = " "
NEWLINE = "\n"


VALID_COLORS = {'w', 'b'}
VALID_PIECES = {'K', 'Q', 'R', 'B', 'N', 'P'}

CELL_PIXEL_SIZE = 100
DEFAULT_MOVE_DURATION = 1000

CMD_CLICK = "click"
CMD_WAIT = "wait"
CMD_PRINT = "print board"

STATE_ACTIVE = "ACTIVE"
STATE_GAME_OVER = "GAME_OVER"


# הודעות שגיאה קבועות
ERROR_UNKNOWN_TOKEN = "ERROR UNKNOWN_TOKEN"
ERROR_ROW_WIDTH_MISMATCH = "ERROR ROW_WIDTH_MISMATCH"
ERROR_INVALID_DIMENSIONS = "ERROR_INVALID_DIMENSIONS"
ERROR_EMPTY_INPUT = "ERROR_EMPTY_INPUT"
